
---
title: "FIFA_Analysis"
author: "CrystalMeth"
date: "Nov 19, 2019"
output:
  html_document:
    number_sectiond: yes
    toc: yes
    toc_float:
      collapsed: no
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)

```


```{r}
fifa <- read.csv('data.csv')
```


```{r}
positions_names <- c("LS", "ST", "RS", "LW", "LF", "CF", "RF", "RW", "LAM", "CAM", "RAM", "LM", "LCM", "CM", "RCM", "RM", "LWB", "LDM", "CDM", "RDM", "RWB", "LB", "LCB", "CB", "RCB", "RB")
skills_names <- c("Crossing", "Finishing", "HeadingAccuracy", "ShortPassing", "Volleys", "Dribbling", "Curve", "FKAccuracy", "LongPassing", "BallControl", "Acceleration", "SprintSpeed", "Agility", "Reactions", "Balance", "ShotPower", "Jumping", "Stamina", "Strength", "LongShots", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Marking", "StandingTackle", "SlidingTackle", "GKDiving", "GKHandling", "GKKicking", "GKPositioning", "GKReflexes")
```

```{r}
for (position in positions_names) {
  fifa[position] <- lapply(fifa[position], function(rating){
    as.integer(substr(rating, 0, 2))
  })
}
```


```{r}
fifa_players <- na.omit(fifa[c(positions_names, skills_names)])
```


```{r}
middle <- c("LAM", "CAM", "RAM", "LM", "LCM", "CM", "RCM", "RM", "LDM", "CDM", "RDM")
left <- c("LS", "LW", "LF", "LAM", "LM", "LCM", "LWB", "LDM", "LB", "LCB")
right <- c("RS", "RF", "RW", "RAM", "RCM", "RM", "RDM", "RWB", "RCB", "RB")
```


```{r}
middle_players <- fifa_players[c(middle, skills_names)]
left_players <- fifa_players[c(left, skills_names)]
right_players <- fifa_players[c(right, skills_names)]
```
```{r}
head(middle_players)

```

```{r}
middle_players$value <- (middle_players$LAM + middle_players$CAM + middle_players$RAM + middle_players$LM + middle_players$LCM + middle_players$CM + middle_players$RCM + middle_players$RM + middle_players$LDM + middle_players$CDM + middle_players$RDM)/11
middle_players$value <- round(middle_players$value)
head(middle_players)
```


```{r}
middle_players_skills <- middle_players[-c(1:11, 46)]
head(middle_players_skills)
```

```{r}
middle_players_skills_scale = data.frame(scale(middle_players_skills))
head(middle_players_skills_scale)
```




```{r}
mps.pr.out =prcomp(middle_players_skills_scale, scale =TRUE)
summary(mps.pr.out)
mps.pr.out$rotation
```

```{r}
biplot(mps.pr.out, scale = 0)
```


```{r}
plot(mps.pr.out, type="l")
```

```{r}
mps.pr.var <- (mps.pr.out$sdev^2)
mps.pve <- mps.pr.var/sum(mps.pr.var)
plot(cumsum(mps.pve), xlab="Principal Component (standardized)", ylab ="Cumulative Proportion of Variance Explained",ylim=c(0,1),type="b")
```



```{r}
head(middle_players_skills_scale)
```

```{r}
mps.pr.out$rotation
```

```{r}
mp.pca <- cbind(middle_players[46], data.frame(mps.pr.out$x))
head(mp.pca)
```

```{r}
mp.pcr1 <- lm(value ~., data = mp.pca)
summary(mp.pcr1)
```

```{r}
mp.pcr2 <- lm(value ~ PC1 + PC2 + PC3, data = mp.pca)
summary(mp.pcr2)
```

```{r}
anova(mp.pcr1, mp.pcr2)
```

```{r}
library(pls)
```

```{r}
library("FactoMineR")
library("factoextra")
```

```{r}
PCA(middle_players_skills_scale, ncp = 5, graph = TRUE)
```

```{r}
res.mp.pca <- PCA(middle_players_skills_scale, graph = FALSE)
print(res.mp.pca)
```


```{r}
eig.val <- get_eigenvalue(res.mp.pca)
eig.val
```

```{r}
fviz_eig(res.mp.pca, addlabels = TRUE, ylim = c(0, 40))
```

```{r}
var <- get_pca_var(res.mp.pca)
var
```

```{r}
fviz_pca_var(res.mp.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )
```

```{r}
library("corrplot")
corrplot(var$cos2, is.corr=FALSE)
```

```{r}
fviz_cos2(res.mp.pca, choice = "var", axes = 1:2)
```

```{r}
head(var$contrib, 4)
```

```{r}
corrplot(var$contrib, is.corr=FALSE)  
```

```{r}
fviz_contrib(res.mp.pca, choice = "var", axes = 1, top = 10)
# Contributions of variables to PC2
fviz_contrib(res.mp.pca, choice = "var", axes = 2, top = 10)
```

```{r}
fviz_contrib(res.mp.pca, choice = "var", axes = 1:2, top = 10)
```

```{r}
fviz_pca_var(res.mp.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )
```

```{r}
fviz_pca_ind(res.mp.pca, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE 
             )
```


```{r}
fviz_pca_ind(res.mp.pca, pointsize = "cos2", 
             pointshape = 21, fill = "#E7B800",
             repel = TRUE 
             )
```



